Controllers/OnlineShoppingMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using OSEntitiesLib;
using OSBusinessLayerLib;
using Newtonsoft.Json;
//using OnlineShopping.Models;

namespace OnlineShopping.Controllers
{
    public class OnlineShoppingMController : Controller
    {
        // GET: OnlineShoppingM
        public ActionResult Index()
        {
            //localhost connection of API
            Uri uri = new Uri("http://localhost:51563/api/");
            //call API for GET
            using (var client = new HttpClient())
            {
                //sets the base address defines the uri path
                client.BaseAddress = uri;
                var result = client.GetStringAsync("OnlineShopping/GetAllCategories/").Result;
                //to get list of categories
                var lstc = JsonConvert.DeserializeObject<List<ProductCategory>>(result);
                //returns the list of productcategory to "GetAllCategories" view to display
                return View(lstc);
            }
        }
        
        public ActionResult GetProductsByName(string productname)
        {
            //localhost connection of API
            Uri uri = new Uri("http://localhost:51563/api/");
            //call API for Get
            using (var client = new HttpClient())
            {
                //sets the base address defines the uri path
                client.BaseAddress = uri;
                var result = client.GetStringAsync("OnlineShopping/GetProductsByName/" + productname).Result;
                //gets the list of products on searching product name
                var lstpro = JsonConvert.DeserializeObject<List<Products>>(result);
                //returns the list of products to "GetProductByName" view to display
                return View(lstpro);
            }
        }

        public ActionResult GetProductsByCategoryName(string cname)
        {
            //localhost connection of API
            Uri uri = new Uri("http://localhost:51563/api/");
            //call API for Get
            using (var client = new HttpClient())
            {
                //sets the base address defines the uri path
                client.BaseAddress = uri;
                var result = client.GetStringAsync("OnlineShopping/GetProductsByCategoryName/" + cname).Result;
                //gets the list of products on clicking the category name
                var lstpro = JsonConvert.DeserializeObject<List<Products>>(result);
                //returns the list of products to "GetProductsByCategoryName" view to display
                return View("GetProductsByCategoryName", lstpro);
            }
        }
        [HttpGet]
        public ActionResult GetProductDetailsById(int id)
        {
            //localhost connection of API
            Uri uri = new Uri("http://localhost:51563/api/");
            //call API for Get
            using (var client = new HttpClient())
            {
                //sets the base address defines the uri path
                client.BaseAddress = uri;
                var result = client.GetStringAsync("OnlineShopping/GetProductDetailsById/" + id).Result;
                //gets the details of product
                var pro = JsonConvert.DeserializeObject<Products>(result);
                //returns the products to "GetProductDetailsById" to display
                return View(pro);

            }
        }
       
        //[HttpGet]
        //public ActionResult AddToCart()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult AddToCart(CartItems item)
        //{
        //    if (Session["cart"] == null)
        //    {
        //        List<CartItems> items = new List<CartItems>();
        //        items.Add(item);
        //        Session.Add("cart", items);
        //    }
        //    else
        //    {
        //        var cartList = (List<CartItems>)Session["cart"];
        //        cartList.Add(item);
        //        Session["cart"] = cartList;
        //    }
        //    // return View();
        //    return RedirectToAction("DisplayCart", new { id = item.ProductId });
        //}
        //public ActionResult DisplayCart()
        //{
        //    Uri uri = new Uri("http://localhost:51563/api/");
        //    var cartList = (List<CartItems>)Session["cart"];
        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = uri;
        //        var result = client.PostAsJsonAsync<List<CartItems>>("OnlineShopping/", cartList).Result;
        //        if (result.IsSuccessStatusCode == true)
        //        {
        //            ViewData.Add("msg", "List are posted");
        //        }
        //        else
        //        {
        //            ViewData.Add("msg", "Something went wrong");
        //        }

        //    }
        //    return View(cartList);

        //}
        //[HttpGet]
        //[Route("api/OnlineShopping/DeletefromCart")]
        //public ActionResult DeletefromCart(int id)
        //{
        //    var cartList = (List<CartItems>)Session["cart"];
        //    var item = cartList.Where(o => o.ProductId == id).FirstOrDefault();
        //    cartList.Remove(item);
        //    Session["cart"] = cartList;
        //    return RedirectToAction("Index");
        //}


        //this action used to add the products in cart 
        public ActionResult AddToCarts(int id,string name)
        {
            Session["cart_values"] = Session["cart_values"] + id.ToString() + ",";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// This method displays the products which are in cart list
        /// </summary>
        /// <param name="list">it is used to pass the cartlist whose record is to be selected</param>
        /// <returns>products are found</returns>
        public ActionResult ViewCart(string list)
        {
            var items = Session["cart_values"];
            if(items == null)
            {
                ViewBag.Message = "No products to display";
                items = "0";
            }
            else { ViewBag.Message = ""; }
            OSBusinessLayer obj = new OSBusinessLayer();
            var lstproduct = obj.ViewCart(items.ToString());
            return View(lstproduct);                                  
        }
        //This action is used to delete the items in cart
        public ActionResult DeleteFromCart(int id)
        {
            string items = Session["cart_values"].ToString();
            string[] selections=items.Split(new char[]{ ','});
            var list = new List<string>(selections);
            list.Remove(id.ToString());
            list.RemoveAll(s => string.IsNullOrWhiteSpace(s));
            Session["cart_values"] = "";
            for(int i =0;i<list.Count;i++)
            {
                Session["cart_values"] = Session["cart_values"] + list[i] + ",";
            }
            return RedirectToAction("ViewCart");            
        }
        //this action is used to order the product
        public ActionResult OrderNow()
        {
            return View();
        }



    }
}
        
    


Views/OnlineShoppingM/GetProductDetailsById.cshtml
@model OSEntitiesLib.Products

@{
    ViewBag.Title = "GetProductDetailsById";
}


<div align="center" style="background-color:palegreen;color:black">
    <h1>@Html.ActionLink("Online Shopping", "Index")</h1><br />
    <form method="post" action="GetProductsByName">
        <center>
            @*<img width="50" height="50" src="~/images/cart.jpg"/>*@
            <input type="text" name="productname" placeholder="Search products" width="200" />
            <input type="submit" value="search" /><br />
        </center>
    </form>
</div>
<div align="center" style="background-color:papayawhip;color:black">
    @using (Html.BeginForm("AddToCarts", "OnlineShoppingM"))
    {
        <form method="post" action="GetProductDetailsById">
            <table>
                <tr>
                    <td style="color:black">
                        <h2> Product Details</h2>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img src="~/images/@Model.Picture" width="200" height="200" />
                    </td>
                    <td>
                        <b>Product Name</b> : @Html.DisplayFor(model => model.ProductName)<br />

                        <b>Price</b> : @Html.DisplayFor(model => model.Price)<br />
                        <b>Content</b> : @Html.Raw(Model.Content)<br />

                    </td>
                </tr>
            
        <tr>
        <td>
            <div>
                @Html.ActionLink("Add To Cart", "AddToCarts", new { id = Model.ProductId, name = Model.ProductName }, new { @class = "btn btn-primary" })
            </div>
        </td>
            </tr>
        </table>
        </form>

    }
</div>




Views/OnlineShoppingM/GetProductsByCategoryName.cshtml
@model IEnumerable<OSEntitiesLib.Products>

@{
    ViewBag.Title = "GetProductsByCategoryName";
}

<div align="center" style="background-color:palegreen;color:white">
    <h1>@Html.ActionLink("Online Shopping", "Index")</h1><br />
    <form method="post" action="GetProductsByName">
        <center>
            @*<img width="50" height="50" src="~/images/cart.jpg"/>*@
            <input type="text" name="productname" placeholder="Search products" width="200" />
            <input type="submit" value="search" /><br />
        </center>
    </form>
</div>
<div align="center" style="background-color: papayawhip;color: black">
    <table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Picture) :
                
                
                    <a href="GetProductDetailsById?id=@item.ProductId">
                        <img src="~/images/@item.Picture" width="100" height="100" />
                    </a>

                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Price) :
                
                
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            </tr>

        }</br>

    </table>
    </div>
   

Views/OnlineShoppingM/GetProductsByName.cshtml
@model IEnumerable<OSEntitiesLib.Products>

@{
    ViewBag.Title = "GetProductsByName";
}


<div align="center" style="background-color:palegreen;color:white">
    <h1>@Html.ActionLink("Online Shopping", "Index")</h1><br />
    <form method="post" action="GetProductsByName">
        <center>
            
            <input type="text" name="productname" placeholder="Search products" width="200" />
            <input type="submit" value="search" /><br />
        </center>
    </form>
</div>
<div align="center" style="background-color: papayawhip;color: black">

    <table class="table">
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.CategoryId)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    <a href="GetProductDetailsById?id=@item.ProductId">
                        <img src="~/images/@item.Picture" width="200" height="200" />
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
                        @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
                    </td>*@
            </tr>
        }

    </table>
    </div>

Views/OnlineShoppingM/Index.cshtml
@model IEnumerable<OSEntitiesLib.ProductCategory>

@{
    ViewBag.Title = "Index";
}


<div align="center" style="background-color:palegreen;color:white">
    <h1>@Html.ActionLink("Online Shopping", "Index")</h1>
    <h5>@Html.ActionLink("MyCart","ViewCart")</h5>
     <form method="post" action="GetProductsByName">
         <center>
          @*<img width="50" height="50" src="~/images/cart.jpg"/>*@
           <input type="text" name="productname" placeholder="Search products" width="200" />
           <input type="submit" value="search" /><br />
          </center>
     </form>
</div>

    @foreach (var item in Model)
    { 
  <form method="get" action="~/OnlineshoppingM/GetProductsByCategoryName">
    <a href="GetProductsByCategoryName?@item.CategoryId&cname=@item.CategoryName">
        @Html.DisplayFor(modelItem => item.CategoryName)

    </a>
  </form>                    
    }


<div align="center" style="background-color:cadetblue;color:black">

    <h1>Home Page</h1>
    <img src="~/images/onlineshopping.jpg" width="800" height="500" />
</div>

@*<table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <form method="get" action="~/Onlineshopping/GetProductsByCName">
                        <a href="GetProductsByCName?@item.CategoryId&cname=@item.CategoryName">
                            @Html.DisplayFor(modelItem => item.CategoryName)<br />

                        </a>
                    </form>
                </td>
            </tr>
        }
    </table>*@



@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>*@

Views/OnlineShoppingM/OrderNow.cshtml

@{
    ViewBag.Title = "OrderNow";
}


<div style="background-color:antiquewhite">
    <h2 style="color:darkblue"> !!! Your order has placed Successfully !!!</h2>
    <p style="color:crimson">Click on Home...@Html.ActionLink("Home","Index")</p>
</div>


Views/OnlineShoppingM/ViewCart.cshtml
@model IEnumerable<OSEntitiesLib.Products>

@{
    ViewBag.Title = "ViewCart";
}

<div align="center" style="background-color:antiquewhite">
    <h2 style="color:crimson"> Cart Items</h2>
   
</div>

<p>
    @Html.ActionLink("Home", "Index")
</p>
@if (ViewBag.Message == "")
{
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Content)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            <img src="~/images/@item.Picture" width="200",height="200"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>*@
        <td>
            @Html.ActionLink("Delete","DeleteFromCart",new { id = item.ProductId })

        </td>
        <td>
            @Html.ActionLink("Order Now","OrderNow")
        </td>
    </tr>
}

</table>
}
else
{
    <h1>@ViewBag.Message</h1>
}